import json
import base64
import urllib.request
import urllib.error

SERVER_URL = "SERVER_URL"  # replace with actual IP generated by proxy_server.py

def call_llm(messages, model="MODEL_NAME"):
    """Send messages to the LLM proxy and return the response content."""
    payload = {'messages': messages, 'model': model}
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(f"{SERVER_URL}/chat", data=data, headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req) as response:
            resp = json.loads(response.read().decode('utf-8'))
            return resp.get('content')
    except urllib.error.URLError as e:
        print(f"LLM proxy error: {e}")
        return None

def text_with_image(image, obj):
    with open(image, "rb") as f:
        image_b64 = base64.b64encode(f.read()).decode('utf-8')
    text = f"YOUR_PROMPT"
    messages = [{
        "role": "user",
        "content": [
            {"type": "text", "text": text},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}}
        ]
    }]
    return call_llm(messages)

def text_only(obj):
    text = f"YOUR_PROMPT"
    messages = [{"role": "user", "content": text}]
    return call_llm(messages)